### ISSUE TITLE
Return 422 on validation errors

### ISSUE THREAD

**Issue by notramo** [martenframework/marten#167] opened 2024-02-21 12:27 UTC
When submitting an invalid form, 200 status is returned with the rendered HTML that contains the error message. However, when using [Turbo](https://turbo.hotwired.dev), the page is not morphed with the new HTML, but the old version is kept. [This issue indicates](https://github.com/hotwired/turbo/issues/246) that it is an intended behavior in Turbo, because form submissions should in most cases return a redirect, 204 (no content), or 4xx error.
From [Turbo docs](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission):
> The reason Turbo doesn’t allow regular rendering on 200’s from POST requests is that browsers have built-in behavior for dealing with reloads on POST visits where they present a “Are you sure you want to submit this form again?” dialogue that Turbo can’t replicate. Instead, Turbo will stay on the current URL upon a form submission that tries to render, rather than change it to the form action, since a reload would then issue a GET against that action URL, which may not even exist

Changing error status to 422 would be not only a Turbo workaround, but would also comply with the sandard, since 200 means OK, which indicates that no error happened while the rendered HTML contains error messages.

**Comment by ellmetha** [comment] 2024-02-21 12:53
This is not a bug so I am going to remove the `Bug` label and use `Discussion` instead. 🙂 

Generic views making use of schemas indeed return a 200 response with the schema in case it is invalid so that the template can re-render the invalid schema and showcase validation errors to end-users. This is because these views simply are built in a way to support classic form display/validation actions initiated by end-users (they re-render the form when it's invalid, and otherwise they redirect to a success route in case it's valid). 

I doubt this default behavior is ever going to change, but we can make it easier to override response codes used in various scenarios by adding a new dedicated class method or something along those lines. In the meantime, one could leverage [schema handler callbacks](https://martenframework.com/docs/handlers-and-http/callbacks#schema-handler-callbacks) to fine-tune the responses returned in case of valid/invalid schemas.

**Comment by ellmetha** [comment] 2024-02-21 23:37
@notramo Using a specific status code over another is always debatable and subject to interpretation. Some frameworks behave like Marten when processing invalid forms, some others return 422 responses, and some others have different behaviors too. What you are asking for is a breaking change technically. I think I am willing to consider it for the 0.5 release as it seems this would be the most pragmatic approach moving forward (given that it would make it easier to integrate with various tools).

**Comment by notramo** [comment] 2024-02-22 10:43
What current use cases would it break? Is there some client-side mechanism that requires an OK response in case of error?

**Comment by notramo** [comment] 2024-02-22 11:09
I checked the code, and it was a simple fix (1 line change), so instead of explaining, I opened a PR (#168).
Tested it with Turbo and also without it. It works in both cases without breaking anything.
I don't think it's much of a breaking change as browser behavior does not change. Also, it's not possible in JS to get the status code of the response that contains the current HTML document. It's only possible for `fetch()` calls to see the status code, but it's not an API response, so the only use case I can think of using `fetch()` is client-side navigation. The most obvious example for this is Turbo (which instead of breaking by this change, it's fixed), and since it fullfills most of the use cases, custom implementations are unlikely to exist.

**Comment by ellmetha** [comment] 2024-02-22 11:33
> What current use cases would it break? Is there some client-side mechanism that requires an OK response in case of error?

This is not really the point. This is a backward incompatible change and this needs to be documented as such. 🤷

**Comment by notramo** [comment] 2024-02-22 11:34
Where should I add documentation? Should it go into the same PR?

**Comment by ellmetha** [comment] 2024-02-22 13:00
The change was added in. fdb517d31d4eb5e6c317e7a99dd6bb2e14dfe422 and release notes were updated accordingly. We can close this now!
Thanks @notramo for bringing this up!

**Closed by ellmetha** 2024-02-22 13:00 UTC
Labels: Discussion, HTTP, Handlers
